

services:
  time-traveler:
    build: .
    container_name: time_traveler_cli
    stdin_open: true     # Keeps STDIN open (for interactive CLI)
    tty: true            # Allocates a pseudo-TTY (important for terminal input/output)
    volumes:
      - .:/app           # Optional: Mount local project to container for live changes
