version: "3.9"

services:
  time-traveler:
    build: .
    container_name: time_traveler_cli
    stdin_open: true       # Keeps STDIN open (interactive mode)
    tty: true              # Enables terminal input/output
    command: ./bin/time_traveler
    volumes:
      - .:/app             # Mount current directory into container (optional for live changes)
